version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: env.user
      POSTGRES_PASSWORD: env.password
      POSTGRES_DB: env.db
    volumes:
      - ./data:/var/lib/postgresql/data
